#!/bin/bash
# This is bench
# Automatically benchmark cuda performance for the fxgpu repo
# Usage: bench [-o SYNCOP] [MAKE_OPTIONS]
#        if "-o SYNCOP" is given, SYNCOP is passed to cuda_correltor as syncOp
# Output: Writes xGPU sizing info and cube_benchmark.log to stdout

exec 3>&1
exec 1>/dev/null
exec 2>/dev/null

syncOp=1 # Dump
if [ "${1}" == "-o" ]
then
  shift
  syncOp=$1
  shift
fi

make clean
make cuda_correlator CUBE_COUNT_MODE=1 OSTYPE=$OSTYPE "$@"
./cuda_correlator -o $syncOp

make clean
make cuda_correlator CUBE_TIME_MODE=1 OSTYPE=$OSTYPE "$@"
./cuda_correlator -o $syncOp

make clean
make cuda_correlator CUBE_ASYNC_COUNT_MODE=1 OSTYPE=$OSTYPE "$@"
./cuda_correlator -o $syncOp

make clean
make cuda_correlator CUBE_ASYNC_TIME_MODE=1 OSTYPE=$OSTYPE "$@"
./cuda_correlator -o $syncOp

# Rebuild a non-benchmarking version
make clean
make all OSTYPE=$OSTYPE "$@"

exec 1>&3

# Display results
# Use less (or more) to page output if desired
echo '==============================='
echo 'xGPU Sizing Parameters'
echo '==============================='
make show OSTYPE=$OSTYPE "$@"
echo
cat cube_benchmark.log
cat cube_async_benchmark.log
